# Dependencies
markdown:         kramdown #redcarpet
highlighter:      Pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Jamie Wilcox'
tagline:          'Instructional Designer'
description:      'Scientist | Engineer | Educator'
url:              https://yellowcrayon.github.io
baseurl:          https://yellowcrayon.github.io/

author:
  name:           'Jamie Wilcox'
  url:            https://www.linkedin.com/in/jamianne-wilcox

paginate:         5

future:           true

# Custom vars
#version:

#github:
#  repo:

gems: [jekyll-paginate]
